### ISSUE TITLE
question about paper

### ISSUE THREAD

**Issue by monster-ghost** [ZHKKKe/DualStudent#5]
I would like to know that How to understand 
" the outputs of these two models may vary widely, and applying the consistency constraint directly will cause them to collapse into each other by exchanging the wrong knowledge"

Here "cause them to collapse into each other" means what?

Does it Mean that imposing consistency on the output of two networks will cause the two networks to converge the same? Then why doesn't EMA have this problem.
I don't understand it very well.

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention. 

`cause them to collapse into each other` means the two models will bias each other, and both of them will have very bad performance. Such a problem is not existing in EMA because EMA is an ensemble strategy, which means the weights of the two models are related.

You can replace the stabilization constraint to the consistency constraint to validate this thing.

**Comment by monster-ghost** [comment]
“two models will bias each other” Is it because the two models get on each other's wrong predictions? 
So the dual teacher sets up a stable sample.
Do I understand this correctly?

**Comment by ZHKKKe** [comment]
**Q1: “two models will bias each other” Is it because the two models get on each other's wrong predictions?**
Yep. The  wrong predictions have a huge negtive impact for the dual structure.
